name = "Delivery app"
# остальное можешь оставить как в основном, но главное:
# 1) убрать webhook subscriptions
# 2) убрать app_proxy

[access_scopes]
scopes = "read_products,write_products,read_metafields,write_metafields"

[webhooks]
api_version = "2026-01"

[build]
automatically_update_urls_on_dev = false
