name = "Delivery app"
# остальное можешь оставить как в основном, но главное:
# 1) убрать webhook subscriptions
# 2) убрать app_proxy

[access_scopes]
scopes = "write_products,read_metaobjects,write_metaobjects,read_metaobject_definitions,write_metaobject_definitions"

[webhooks]
api_version = "2026-01"

[build]
automatically_update_urls_on_dev = false
